In [1]:
# import standard packages
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.mlab import frange

# To make the display prettier
%precision 3

'%.3f'

In [2]:
# Note that with "arange" the last value is NOT included!
x = np.arange(1,5,0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [3]:
# "linspace" produces a given number of linearly spaced numbers
y = np.linspace(0,1,11)
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [4]:
# "frange" includes the last value  # 这个包括最后一个
z = frange(1,3)
z

/Users/chengkai/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: MatplotlibDeprecationWarning: numpy.arange
  


array([1., 2., 3.])

In [5]:
# Unlike MATLAB, Python by default generates vectors, NOT matrices!
zero_vector = np.zeros(3)
zero_vector

array([0., 0., 0.])

In [6]:
# "np.zeros" and "np.ones" generate zeros and ones, respecitvely.
# They only take ONE input argument, which can be a number or a tuple:
zero_matrix = np.zeros( (3,3))# Rotation matrix for a rotation by 30 deg
alpha = np.deg2rad(30)
rot_mat = np.array([[np.cos(alpha), -np.sin(alpha)],
                    [np.sin(alpha), np.cos(alpha)]])

# Note that there are two ways to specify a matrix multiplication
vec = np.r_[1,0]
vec_rotated = rot_mat.dot(vec)
vec_rotated_2 = rot_mat @ vec # for Python >3.5

# Show the results
print(rot_mat)
print('I rotated {0} into {1}'.format(str(vec), str(vec_rotated)))
np.all(vec_rotated == vec_rotated_2)
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Note: "np.random.randn" in contrast can use more than one input argument:
np.random.randn(3,2)

array([[ 0.268, -0.608],
       [-0.864, -0.344],
       [ 0.003, -0.652]])

In [8]:
# Here an example of how to conveniently generate a matrix of column vectors:
phi = np.deg2rad(np.arange(0,360,30))
sines = np.sin(phi)
cosines = np.cos(phi)

data_mat = np.column_stack((sines, cosines))

print(np.round(data_mat, 2))

[[ 0.    1.  ]
 [ 0.5   0.87]
 [ 0.87  0.5 ]
 [ 1.    0.  ]
 [ 0.87 -0.5 ]
 [ 0.5  -0.87]
 [ 0.   -1.  ]
 [-0.5  -0.87]
 [-0.87 -0.5 ]
 [-1.   -0.  ]
 [-0.87  0.5 ]
 [-0.5   0.87]]


In [9]:
# A row-vector can be generated like this ...
row_vector = np.array([1,2,3])
row_vector

array([1, 2, 3])

In [10]:
# ... or equivalently like that
row_vector2 = np.r_[3,4,5]
row_vector2

array([3, 4, 5])

In [12]:
# I know the syntax for generating column-vectors are all a bit weird :(
col_vector = np.c_[[4,5,6]]
col_vector

array([[4],
       [5],
       [6]])

In [13]:
# This one uses the command "np.newaxis" to generate a column vector ....
row_vector[..., np.newaxis]

array([[1],
       [2],
       [3]])

In [14]:
# ... and here is how to use the "reshape" command: the "-1" means "however many there are":
np.reshape(row_vector, (-1,1))

array([[1],
       [2],
       [3]])

In [15]:
# Rotation matrix for a rotation by 30 deg
alpha = np.deg2rad(30)
rot_mat = np.array([[np.cos(alpha), -np.sin(alpha)],
                    [np.sin(alpha), np.cos(alpha)]])

# Note that there are two ways to specify a matrix multiplication
vec = np.r_[1,0]
vec_rotated = rot_mat.dot(vec)
vec_rotated_2 = rot_mat @ vec # for Python >3.5

# Show the results
print(rot_mat)
print('I rotated {0} into {1}'.format(str(vec), str(vec_rotated)))
np.all(vec_rotated == vec_rotated_2)

[[ 0.866 -0.5  ]
 [ 0.5    0.866]]
I rotated [1 0] into [0.866 0.5  ]


True

In [16]:
# Generate some data
data = np.arange(15).reshape((5,3))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
# overall mean
np.mean(data)

7.0

In [18]:
# mean over all rows
np.mean(data, axis=0)

array([6., 7., 8.])

In [19]:
# Now we use "broadcasting" to subtract the mean of each column:
# if the second index matches, the operation is applied to each row:
data - np.mean(data, axis=0)

array([[-6., -6., -6.],
       [-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.],
       [ 6.,  6.,  6.]])

In [20]:
# This only works on the last index!
data - np.mean(data, axis=1)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [22]:
# If you want to know confidence intervals, best switch to *pandas*
# Pandas is mainly used for statistics and worksheet-like data
import pandas

# The calculation of OLS has been moved to *statsmodels* now
import statsmodels.formula.api as smf

# Note that this is an advanced topic, and requires new data structures
# such ad "DataFrames" and "ordinary-least-squares" or "ols-models".
myDict = {'x':tHigh, 'y':xHigh}
df = pandas.DataFrame(myDict)
model = smf.ols('y~x', df).fit()
print(model.summary())

NameError: name 'tHigh' is not defined